let body = document.querySelector("body")
let scratchpadInputField = document.querySelector(".scratchpadInputField")
let allTodoSect = document.querySelector(".allTodoSect")
// let allCompletedSect = document.querySelector(".allCompletedSect")
let allDeletedSect = document.querySelector(".allDeletedSect")
let newTodoCtnr = document.querySelector(".newTodoCtnr")
let newTodoMainCtnr = document.querySelector(".newTodoMainCtnr")
let newTodoForm = document.querySelector(".newTodoForm")
let newTodoTitleForm = document.querySelector(".newTodoTitleForm")
let formInputField = document.querySelector(".formInputField")
let addLiBtn = document.querySelector(".addLiBtn")
let formTitleInputField = document.querySelector(".formTitleInputField")
let addTitleBtn = document.querySelector(".addTitleBtn")
let saveNCloseBtn = document.querySelector(".saveNCloseBtn")
let createNewTodoBtn = document.querySelector(".createNewTodoBtn")
let newTodoUL = document.querySelector(".newTodoUL")

